CREATE TABLE IF NOT EXISTS clubs (
    id TEXT PRIMARY KEY NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS stadiums (
    id TEXT PRIMARY KEY NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS leagues (
    id TEXT PRIMARY KEY NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS seasons (
    id TEXT PRIMARY KEY NOT NULL,
    data TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS season_state (
    season_id TEXT PRIMARY KEY NOT NULL,
    data TEXT NOT NULL
);
