[package]
name = "openfootmanager_db"
version = "0.1.0"
edition = "2024"

[dependencies]
openfootmanager_core = { path = "../core" }
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls", "macros", "migrate"] }
tokio = { version = "1.37", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "2.0"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
